// --- EXERCISE DATABASE ---
const exerciseDB = [
    { id:101,name:"Barbell Bench Press",muscle:"Chest",desc:"Lie flat. Press bar up." }, { id:102,name:"Incline DB Press",muscle:"Chest",desc:"Bench 30 deg. Press DBs." },
    { id:103,name:"Weighted Dips",muscle:"Chest",desc:"Lower body to 90 deg." }, { id:104,name:"Cable Flys",muscle:"Chest",desc:"Squeeze handles together." },
    { id:105,name:"Decline Press",muscle:"Chest",desc:"Head lower than feet." }, { id:106,name:"DB Pullover",muscle:"Chest",desc:"DB behind head." },
    { id:201,name:"Deadlift",muscle:"Back",desc:"Hinge hips. Lift heavy." }, { id:202,name:"Pull Ups",muscle:"Back",desc:"Chin over bar." },
    { id:203,name:"Barbell Row",muscle:"Back",desc:"Pull bar to stomach." }, { id:204,name:"Lat Pulldown",muscle:"Back",desc:"Pull to upper chest." },
    { id:205,name:"Seated Row",muscle:"Back",desc:"Pull V-handle to waist." }, { id:206,name:"T-Bar Row",muscle:"Back",desc:"Chest supported row." },
    { id:301,name:"Barbell Squat",muscle:"Legs",desc:"Deep squat." }, { id:302,name:"Leg Press",muscle:"Legs",desc:"Push weight." },
    { id:303,name:"RDL",muscle:"Legs",desc:"Hinge hips." }, { id:304,name:"Split Squat",muscle:"Legs",desc:"One leg behind." },
    { id:305,name:"Hack Squat",muscle:"Legs",desc:"Machine squat." }, { id:306,name:"Lunges",muscle:"Legs",desc:"Step forward." },
    { id:701,name:"Hip Thrusts",muscle:"Glutes",desc:"Bar on hips. Thrust." }, { id:702,name:"Kickbacks",muscle:"Glutes",desc:"Kick leg back." },
    { id:703,name:"Cable Pull Through",muscle:"Glutes",desc:"Rope between legs." }, { id:704,name:"Sumo Squat",muscle:"Glutes",desc:"Wide stance." },
    { id:705,name:"Step Ups",muscle:"Glutes",desc:"Drive through heel." }, { id:706,name:"Frog Pumps",muscle:"Glutes",desc:"Feet together, lift." },
    { id:401,name:"Overhead Press",muscle:"Shoulders",desc:"Press overhead." }, { id:402,name:"Lateral Raises",muscle:"Shoulders",desc:"Lift to side." },
    { id:403,name:"Face Pulls",muscle:"Shoulders",desc:"Rope to face." }, { id:404,name:"Front Raise",muscle:"Shoulders",desc:"Lift to front." },
    { id:501,name:"Tricep Pushdown",muscle:"Triceps",desc:"Push cable down." }, { id:502,name:"Skullcrushers",muscle:"Triceps",desc:"Bar to forehead." },
    { id:503,name:"Overhead Ext",muscle:"Triceps",desc:"DB behind head." }, { id:504,name:"Close Grip Bench",muscle:"Triceps",desc:"Hands narrow." },
    { id:601,name:"Barbell Curl",muscle:"Biceps",desc:"Curl to chest." }, { id:602,name:"Hammer Curl",muscle:"Biceps",desc:"Palms facing." },
    { id:603,name:"Preacher Curl",muscle:"Biceps",desc:"Arm on pad." }, { id:604,name:"Incline Curl",muscle:"Biceps",desc:"Seated incline." },
    { id:310,name:"Leg Extension",muscle:"Legs",desc:"Kick up." }, { id:311,name:"Leg Curl",muscle:"Legs",desc:"Heels to butt." },
    { id:312,name:"Calf Raises",muscle:"Calves",desc:"Lift heels." },
    { id:801,name:"Plank",muscle:"Core",desc:"Hold straight." }, { id:802,name:"Leg Raise",muscle:"Core",desc:"Lift legs." },
    { id:803,name:"Crunches",muscle:"Core",desc:"Squeeze abs." }, { id:804,name:"Russian Twist",muscle:"Core",desc:"Twist side to side." }
];

const routines = {
    male: { shred: { 1:{focus:"Push A",ex:[101,102,103,104,401,105,402,501,502,404,801,803]}, 2:{focus:"Pull A",ex:[201,202,203,204,205,206,601,602,403,603,802,804]}, 3:{focus:"Legs A",ex:[301,302,303,304,305,307,310,311,312,701,801,802]}, 4:{focus:"Push B",ex:[102,101,106,107,404,108,402,503,504,501,803,804]}, 5:{focus:"Pull B",ex:[206,204,203,201,205,202,604,601,403,602,801,802]}, 6:{focus:"Legs B",ex:[303,301,306,302,304,305,311,310,312,702,803,804]}, 0:{focus:"Rest",ex:[]} } },
    female: { tone: { 1:{focus:"Glutes A",ex:[701,303,702,704,705,306,301,402,102,204,801,802]}, 2:{focus:"Upper Body",ex:[401,102,204,205,104,402,501,601,503,602,803,804]}, 3:{focus:"Quads/Calves",ex:[301,302,304,305,306,308,312,310,703,706,801,803]}, 4:{focus:"Full Body A",ex:[301,201,101,401,304,204,501,601,402,701,802,804]}, 5:{focus:"Full Body B",ex:[303,102,203,701,306,205,502,602,403,704,801,803]}, 6:{focus:"Active Rest",ex:[]}, 0:{focus:"Rest",ex:[]} } }
};

const foodLibrary = [
    { n: "egg", p:6, c:0.6, f:5, cal:72 }, { n: "bread", p:3, c:15, f:1, cal:80 }, { n: "chicken", p:31, c:0, f:3.6, cal:165 },
    { n: "rice", p:2.7, c:28, f:0.3, cal:130 }, { n: "beans", p:8, c:20, f:0.5, cal:110 }, { n: "beef", p:26, c:0, f:17, cal:250 },
    { n: "salmon", p:20, c:0, f:13, cal:208 }, { n: "tuna", p:25, c:0, f:1, cal:110 }, { n: "oats", p:5, c:27, f:3, cal:150 },
    { n: "banana", p:1.3, c:27, f:0.4, cal:105 }, { n: "apple", p:0.5, c:25, f:0.3, cal:95 }, { n: "potato", p:4, c:37, f:0.2, cal:160 },
    { n: "broccoli", p:3, c:6, f:0.4, cal:35 }, { n: "spinach", p:2.9, c:3.6, f:0.4, cal:23 }, { n: "yogurt", p:10, c:4, f:0, cal:59 },
    { n: "cheese", p:7, c:1, f:9, cal:113 }, { n: "protein shake", p:24, c:3, f:1, cal:120 }, { n: "almonds", p:6, c:6, f:14, cal:164 }, { n: "avocado", p:2, c:9, f:15, cal:160 }
];

const mealIdeas = {
    Breakfast: [ { t:"Eggs & Toast", d:"2 Eggs, 2 slices whole wheat toast", m:"P:18 C:30 F:12" }, { t:"Oatmeal Power Bowl", d:"Oats, protein powder, berries", m:"P:30 C:40 F:6" }, { t:"Greek Yogurt Parfait", d:"Yogurt, granola, honey", m:"P:20 C:30 F:5" }, { t:"Protein Pancakes", d:"Banana, egg, protein powder", m:"P:25 C:30 F:5" }, { t:"Avocado Toast", d:"Toast, avocado, poached egg", m:"P:15 C:25 F:15" }, { t:"Veggie Omelette", d:"3 egg whites, spinach, peppers", m:"P:20 C:5 F:2" }, { t:"Smoothie", d:"Spinach, apple, protein, almond milk", m:"P:25 C:20 F:5" }, { t:"Breakfast Burrito", d:"Tortilla, eggs, black beans", m:"P:20 C:35 F:12" }, { t:"Cottage Cheese Bowl", d:"Low fat cottage cheese, pineapple", m:"P:25 C:15 F:3" }, { t:"Egg Muffins", d:"Baked eggs with ham and cheese", m:"P:18 C:2 F:10" } ],
    Lunch: [ { t:"Chicken & Rice", d:"Grilled breast, 1 cup white rice", m:"P:35 C:40 F:5" }, { t:"Tuna Salad", d:"Canned tuna, light mayo, lettuce", m:"P:30 C:5 F:10" }, { t:"Turkey Wrap", d:"Turkey slices, tortilla, cheese", m:"P:25 C:30 F:10" }, { t:"Beef Stir Fry", d:"Lean beef, mixed veggies", m:"P:30 C:15 F:12" }, { t:"Quinoa Bowl", d:"Quinoa, chickpeas, cucumber", m:"P:12 C:40 F:8" }, { t:"Lentil Soup", d:"Lentils, carrots, broth", m:"P:15 C:30 F:2" }, { t:"Chicken Caesar", d:"Chicken, romaine, light dressing", m:"P:30 C:10 F:15" }, { t:"Salmon Poke", d:"Raw salmon, rice, edamame", m:"P:25 C:40 F:10" }, { t:"Pasta Primavera", d:"Whole wheat pasta, zucchini, pesto", m:"P:10 C:50 F:12" }, { t:"Hummus Plate", d:"Hummus, pita, grilled veggies", m:"P:12 C:45 F:15" } ],
    Dinner: [ { t:"Steak & Potato", d:"Lean sirloin, baked potato", m:"P:40 C:35 F:15" }, { t:"Salmon & Asparagus", d:"Baked salmon, lemon, asparagus", m:"P:30 C:5 F:15" }, { t:"Chicken Tacos", d:"Corn tortilla, chicken, salsa", m:"P:25 C:30 F:8" }, { t:"Turkey Meatballs", d:"Ground turkey, marinara, zucchini", m:"P:30 C:10 F:10" }, { t:"Shrimp Scampi", d:"Shrimp, garlic, little butter", m:"P:25 C:5 F:10" }, { t:"Burger (No Bun)", d:"Beef patty, lettuce wrap", m:"P:25 C:2 F:18" }, { t:"Cod Fillet", d:"White fish, green beans", m:"P:25 C:5 F:2" }, { t:"Veggie Curry", d:"Tofu, coconut milk, curry paste", m:"P:15 C:20 F:15" }, { t:"Stuffed Peppers", d:"Ground beef, rice, tomato sauce", m:"P:25 C:25 F:10" }, { t:"Pork Chops", d:"Grilled pork loin, sweet potato", m:"P:30 C:25 F:12" } ],
    Snack: [ { t:"Almonds", d:"Handful of raw almonds", m:"P:6 C:6 F:14" }, { t:"Protein Shake", d:"1 scoop whey, water", m:"P:24 C:2 F:1" }, { t:"Apple & Peanut Butter", d:"1 Apple, 1 tbsp PB", m:"P:4 C:25 F:8" }, { t:"Cottage Cheese", d:"Low fat cottage cheese cup", m:"P:20 C:5 F:2" }, { t:"Rice Cake", d:"2 cakes", m:"P:2 C:14 F:0" }, { t:"Hard Boiled Eggs", d:"2 eggs", m:"P:12 C:1 F:10" }, { t:"Greek Yogurt", d:"Plain 0% fat", m:"P:15 C:8 F:0" }, { t:"Hummus & Carrots", d:"2 tbsp hummus, baby carrots", m:"P:3 C:15 F:5" }, { t:"Protein Bar", d:"Generic bar", m:"P:20 C:20 F:8" }, { t:"Edamame", d:"Steamed soybeans", m:"P:10 C:8 F:4" } ]
};

let users = [], activeUserIndex = 0, timerInterval = null, currentTimerVal = 0, currentUnit = 'kg', currentExId = null;

function enterArena() { document.getElementById('splash-screen').style.display='none'; document.getElementById('app-container').style.display='flex'; initApp(); }
function initApp() { try { const s=localStorage.getItem('spartanUsers'); if(s){ users=JSON.parse(s); if(!users[0].nutritionLogs)users[0].nutritionLogs=[]; if(!users[0].completedToday)users[0].completedToday=[]; } else createDefaultUser(); updateUI(); } catch(e){ createDefaultUser(); updateUI(); } }
function createDefaultUser() { users=[{id:Date.now(), name:"Warrior", trainerMode:false, gender:'male', goal:'shred', history:[], nutritionLogs:[], completedToday:[]}]; saveData(); }
function updateUI() { const u=users[activeUserIndex]; document.getElementById('current-user-name').innerText=u.name; const mb=document.getElementById('top-left-menu'); if(u.trainerMode){mb.style.opacity="1";mb.style.pointerEvents="auto";document.getElementById('trainer-caret').style.display="inline";}else{mb.style.opacity="0.5";mb.style.pointerEvents="none";document.getElementById('trainer-caret').style.display="none";} document.getElementById('workout-count').innerText=u.history.length; const t=new Date().toDateString(); if(u.lastLogin!==t){u.completedToday=[]; u.lastLogin=t; saveData();} const logs=u.nutritionLogs.filter(l=>new Date(l.date).toDateString()===t); document.getElementById('cal-display').innerText=logs.reduce((a,b)=>a+(parseInt(b.cal)||0),0); document.getElementById('p-name').value=u.name; document.getElementById('p-gender').value=u.gender; document.getElementById('p-goal').value=u.goal; document.getElementById('p-trainer-mode').checked=u.trainerMode||false; loadDailyRoutine(u); renderWeeklyChart(u); }
function loadDailyRoutine(u) { const d=new Date().getDay(); document.getElementById('day-display').innerText=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][d]; let plan=routines[u.gender||'male'][u.goal||'shred'][d]||{focus:"Rest",ex:[]}; document.getElementById('focus-display').innerText=plan.focus; const l=document.getElementById('todays-routine-list'); l.innerHTML=""; if(plan.ex.length===0){l.innerHTML=`<div style="text-align:center; padding:20px; color:#2ecc71">REST DAY</div>`;return;} plan.ex.forEach((id,i)=>{ const ex=exerciseDB.find(e=>e.id===id); if(ex){ let cls=i<6?"major-ex":(i>=10?"core-ex":"minor-ex"); const c=u.completedToday&&u.completedToday.includes(id); l.innerHTML+=`<div class="routine-item ${cls}"><div style="flex:1" onclick="openTracker(${id})"><b>${ex.name}</b><br><small style="color:#aaa">${ex.muscle}</small></div><div class="check-container" onclick="toggleComplete(${id})"><div class="custom-checkbox ${c?'checked':''}"><i class="fas fa-check" style="display:${c?'block':'none'}; color:black; font-size:12px;"></i></div></div></div>`; } }); }
function renderWeeklyChart(u) { const div=document.getElementById('weekly-chart'); div.innerHTML=""; const days=['S','M','T','W','T','F','S'], now=new Date(); for(let i=6; i>=0; i--){ const d=new Date(); d.setDate(now.getDate()-i); const cnt=u.history.filter(h=>new Date(h.date).toDateString()===d.toDateString()).length; let h=(cnt/20)*100; if(h>100)h=100; if(h<5&&cnt>0)h=10; div.innerHTML+=`<div style="flex:1; display:flex; flex-direction:column; align-items:center;"><div class="chart-bar" style="height:${h}%"></div><div class="chart-day">${days[d.getDay()]}</div></div>`; } }
function openTracker(id) { currentExId=id; const ex=exerciseDB.find(e=>e.id===id); document.getElementById('tracker-modal').style.display='flex'; document.getElementById('m-title').innerText=ex.name; document.getElementById('m-desc').innerText=ex.desc; const u=users[activeUserIndex]; const hist=u.history.filter(h=>h.exId===id); const last=hist[hist.length-1]; document.getElementById('m-ai-msg').innerText=last?`Last: ${last.weight} x ${last.reps}`:"New Exercise"; const t=new Date().toDateString(); const todays=u.history.filter(h=>h.exId===id&&new Date(h.date).toDateString()===t); let h=""; todays.forEach((s,i)=>{ h+=`<div class="history-item"><span>Set ${i+1}: ${s.weight} x ${s.reps}</span><button class="delete-set-btn" onclick="deleteSet('${s.uniqueId}')"><i class="fas fa-trash"></i></button></div>`; }); document.getElementById('sets-history').innerHTML=h||"<small style='color:#777'>No sets today</small>"; }
function saveSet() { const w=document.getElementById('log-w').value, r=document.getElementById('log-r').value; if(!w||!r)return; const uid=Date.now().toString()+Math.floor(Math.random()*1000); users[activeUserIndex].history.push({uniqueId:uid, date:new Date().toISOString(), exId:currentExId, weight:w, reps:r}); saveData(); openTracker(currentExId); }
function deleteSet(uid) { if(!confirm("Delete set?"))return; users[activeUserIndex].history=users[activeUserIndex].history.filter(h=>h.uniqueId!==uid); saveData(); openTracker(currentExId); updateUI(); }
function toggleComplete(id) { const u=users[activeUserIndex]; if(u.completedToday.includes(id))u.completedToday=u.completedToday.filter(x=>x!==id); else{u.completedToday.push(id); startRestTimer(120,"NEXT EXERCISE");} saveData(); updateUI(); }
function startRestTimer(sec,lbl) { clearInterval(timerInterval); currentTimerVal=sec; document.getElementById('rest-overlay').style.display='flex'; document.getElementById('timer-label').innerText=lbl; document.getElementById('timer-countdown').innerText=fmtTime(sec); timerInterval=setInterval(()=>{ currentTimerVal--; document.getElementById('timer-countdown').innerText=fmtTime(currentTimerVal); if(currentTimerVal<=0){ stopTimer(); if(navigator.vibrate)navigator.vibrate(500); playBeep(); alert(lbl+" COMPLETE!"); } },1000); }
function stopTimer() { clearInterval(timerInterval); document.getElementById('rest-overlay').style.display='none'; }
function fmtTime(s) { const m=Math.floor(s/60),sec=s%60; return `${m}:${sec<10?'0'+sec:sec}`; }
function playBeep() { try{const c=new(window.AudioContext||window.webkitAudioContext)();const o=c.createOscillator();o.connect(c.destination);o.frequency.value=800;o.type='sine';o.start();setTimeout(()=>o.stop(),500);}catch(e){} }
function setUnit(u) { currentUnit=u; document.getElementById('unit-kg').className=u==='kg'?'unit-opt active':'unit-opt'; document.getElementById('unit-lbs').className=u==='lbs'?'unit-opt active':'unit-opt'; document.getElementById('weight-label').innerText=`Weight (${u.toUpperCase()})`; if(currentExId)openTracker(currentExId); }
function closeModal() { document.getElementById('tracker-modal').style.display='none'; }
function autoFillMacros() { const v=document.getElementById('food-name').value.toLowerCase().split(' '); let f=null; for(let w of v){f=foodLibrary.find(x=>x.n.includes(w));if(f)break;} if(f){ document.getElementById('m-prot').value=f.p; document.getElementById('m-carb').value=f.c; document.getElementById('m-fat').value=f.f; document.getElementById('m-cal').value=f.cal; }else alert("Not found"); }
function logMeal() { const n=document.getElementById('food-name').value; if(!n)return alert("Enter Name"); users[activeUserIndex].nutritionLogs.push({ id:Date.now(), date:new Date().toISOString(), type:document.getElementById('meal-type').value, name:n, p:parseInt(document.getElementById('m-prot').value)||0, c:parseInt(document.getElementById('m-carb').value)||0, f:parseInt(document.getElementById('m-fat').value)||0, cal:parseInt(document.getElementById('m-cal').value)||0 }); saveData(); updateUI(); updateMacrosDisplay(); document.getElementById('food-name').value=""; document.getElementById('m-cal').value=""; }
function updateMacrosDisplay() { const u=users[activeUserIndex], t=new Date().toDateString(); const l=u.nutritionLogs.filter(x=>new Date(x.date).toDateString()===t); let h="",tp=0,tc=0,tf=0; l.forEach(x=>{ tp+=x.p; tc+=x.c; tf+=x.f; h+=`<div class="meal-log-item"><div class="meal-log-details"><b>${x.type}:</b> ${x.name} (${x.cal} cal)</div><button class="delete-meal-btn" onclick="deleteMeal(${x.id})"><i class="fas fa-trash"></i></button></div>`; }); document.getElementById('macro-display').innerHTML=`<div style="display:flex; justify-content:space-between; background:#222; padding:10px; border-radius:5px;"><span style="color:#3498db">P:${tp}g</span> <span style="color:#2ecc71">C:${tc}g</span> <span style="color:#e74c3c">F:${tf}g</span></div>`; document.getElementById('meal-log-list').innerHTML=h; }
function deleteMeal(id) { if(!confirm("Remove meal?"))return; users[activeUserIndex].nutritionLogs=users[activeUserIndex].nutritionLogs.filter(l=>l.id!==id); saveData(); updateUI(); updateMacrosDisplay(); }
function filterMeals(t) { const c=document.getElementById('meal-prep-container'); c.innerHTML=""; (mealIdeas[t]||[]).forEach(i=>c.innerHTML+=`<div class="meal-prep-card"><b>${i.t}</b><br><small>${i.d}</small><br><span style="color:gold; font-size:10px">${i.m}</span></div>`); }
function showNutriTab(t) { document.getElementById('nutri-track-view').style.display=t==='track'?'block':'none'; document.getElementById('nutri-ideas-view').style.display=t==='ideas'?'block':'none'; if(t==='track')updateMacrosDisplay(); if(t==='ideas')filterMeals('Breakfast'); }
function resetCurrentUserData() { if(!confirm("Reset ALL data for this user?"))return; const u=users[activeUserIndex]; u.history=[]; u.nutritionLogs=[]; u.completedToday=[]; saveData(); updateUI(); alert("Reset Complete"); }
function deleteCurrentUser() { if(!confirm("Delete User?"))return; if(users.length===1)return emergencyReset(); users.splice(activeUserIndex,1); activeUserIndex=0; saveData(); document.getElementById('user-menu').style.display='none'; updateUI(); }
function emergencyReset() { if(confirm("FACTORY RESET APP?")) { localStorage.removeItem('spartanUsers'); location.reload(); } }
function toggleTrainerMode() { users[activeUserIndex].trainerMode=document.getElementById('p-trainer-mode').checked; saveData(); updateUI(); }
function toggleUserMenu() { const m=document.getElementById('user-menu'); m.style.display=m.style.display==='block'?'none':'block'; if(m.style.display==='block'){ const l=document.getElementById('user-list-display'); l.innerHTML=""; users.forEach((u,i)=>l.innerHTML+=`<div class="user-option" onclick="switchUser(${i})"><b>${u.name}</b></div>`); } }
function createNewUser() { const n=prompt("Name:"); if(n){ users.push({id:Date.now(), name:n, trainerMode:false, gender:'male', goal:'shred', history:[], nutritionLogs:[], completedToday:[]}); saveData(); toggleUserMenu(); } }
function switchUser(i) { activeUserIndex=i; document.getElementById('user-menu').style.display='none'; updateUI(); }
function saveProfile() { const u=users[activeUserIndex]; u.name=document.getElementById('p-name').value; u.gender=document.getElementById('p-gender').value; u.goal=document.getElementById('p-goal').value; saveData(); updateUI(); alert("Saved"); }
function filterLibrary() { const t=document.getElementById('search-ex').value.toLowerCase(); const l=document.getElementById('library-list'); l.innerHTML=""; exerciseDB.filter(e=>e.name.toLowerCase().includes(t)).forEach(e=>l.innerHTML+=`<div class="routine-item" onclick="openTracker(${e.id})"><b>${e.name}</b> <small>${e.muscle}</small></div>`); }
function nav(id) { document.querySelectorAll('.tab-content').forEach(e=>e.classList.remove('active')); document.querySelectorAll('nav button').forEach(e=>e.classList.remove('active')); document.getElementById(id).classList.add('active'); if(id==='dashboard')updateUI(); if(id==='library')filterLibrary(); if(id==='nutrition')showNutriTab('track'); }
function saveData() { localStorage.setItem('spartanUsers', JSON.stringify(users)); }